#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="ClipBucket%20v2/clipbucket-2.6-r738.zip"
URL="https://sourceforge.net/projects/clipbucket/files/$VERSION"

dl $URL /usr/local/src

