#!/bin/sh -ex

DB_NAME=clipbucket
DB_USER=clipbucket
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/clipbucket

# unpack and set permissions
mkdir -p $SRC/clipbucket
unzip $SRC/clipbucket-*.zip -d $SRC/clipbucket
mv $SRC/clipbucket/upload $WEBROOT
rm -rf $SRC/clipbucket*
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/files
chown -R www-data:www-data $WEBROOT/cache
chown -R www-data:www-data $WEBROOT/images
chown -R www-data:www-data $WEBROOT/includes

# php.ini tweaks
PHPINI=/etc/php5/apache2/php.ini
sed -i "s|^memory_limit.*|memory_limit = 512M|" $PHPINI
sed -i "s|^post_max_size.*|post_max_size = 256M|" $PHPINI
sed -i "s|^upload_max_filesize.*|upload_max_filesize = 256M|" $PHPINI
sed -i "s|^;date.timezone.*|date.timezone = \"UTC\"|" $PHPINI

# configure apache
a2dissite default
a2ensite clipbucket
a2enmod rewrite

# start services
/etc/init.d/mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# stop services
/etc/init.d/mysql stop

