#!/bin/sh -ex

DB_NAME=clipbucket
DB_USER=clipbucket
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/clipbucket

