#!/bin/sh -ex

DB_NAME=clipbucket
DB_USER=clipbucket
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/clipbucket

# unpack and set permissions
mkdir -p $SRC/clipbucket
unzip $SRC/clipbucket-*.zip -d $SRC/clipbucket
mv $SRC/clipbucket/upload $WEBROOT
rm -rf $SRC/clipbucket*
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/files
chown -R www-data:www-data $WEBROOT/cache
chown -R www-data:www-data $WEBROOT/images
chown -R www-data:www-data $WEBROOT/includes

# php.ini tweaks
PHPINI=/etc/php5/apache2/php.ini
sed -i "s|^memory_limit.*|memory_limit = 512M|" $PHPINI
sed -i "s|^post_max_size.*|post_max_size = 256M|" $PHPINI
sed -i "s|^upload_max_filesize.*|upload_max_filesize = 256M|" $PHPINI
sed -i "s|^;date.timezone.*|date.timezone = \"UTC\"|" $PHPINI

# configure apache
a2dissite default
a2ensite clipbucket
a2enmod rewrite

# start services
/etc/init.d/mysql start
/etc/init.d/apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based install
URL="http://127.0.0.1/cb_install/"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)
DBCONF="dbhost=localhost&dbname=$DB_NAME&dbuser=$DB_USER&dbpass=$DB_PASS&dbprefix="
ADMINCONF="username=$ADMIN_NAME&password=$ADMIN_PASS&email=$EMAIL"

$CURL "${URL}" --data "mode=precheck"
$CURL "${URL}" --data "mode=permission"
$CURL "${URL}" --data "mode=database"
$CURL "${URL}ajax.php" --data "mode=dataimport&$DBCONF"
$CURL "${URL}" --data "mode=dataimport&$DBCONF"
$CURL "${URL}ajax.php" --data "mode=adminsettings&step=structure&$DBCONF"
$CURL "${URL}ajax.php" --data "mode=adminsettings&step=configs&$DBCONF"
$CURL "${URL}ajax.php" --data "mode=adminsettings&step=ads_placements&$DBCONF"
$CURL "${URL}ajax.php" --data "mode=adminsettings&step=countries&$DBCONF"
$CURL "${URL}ajax.php" --data "mode=adminsettings&step=email_templates&$DBCONF"
$CURL "${URL}ajax.php" --data "mode=adminsettings&step=pages&$DBCONF"
$CURL "${URL}ajax.php" --data "mode=adminsettings&step=user_levels&$DBCONF"
$CURL "${URL}ajax.php" --data "mode=adminsettings&step=add_categories&$DBCONF"
$CURL "${URL}ajax.php" --data "mode=adminsettings&step=add_admin&$DBCONF"
$CURL "${URL}ajax.php" --data "mode=adminsettings&step=create_files&$DBCONF"
$CURL "${URL}" --data "mode=adminsettings&$DBCONF"
$CURL "${URL}" --data "mode=sitesettings&$ADMINCONF"
$CURL "${URL}" --data "mode=register&title=TurnKey+ClipBucket&slogan=A+way+to+broadcast+yourself&baseurl=http%3A%2F%2F$DOMAIN"
$CURL "${URL}" --data "mode=finish"

rm -rf $WEBROOT/cb_install
rm -f /tmp/cookie

# tweak settings
cb_set() {
    $MYSQL_BATCH --execute "UPDATE $DB_NAME.config SET value=\"$2\" WHERE name=\"$1\";"
}

cb_set "use_crons" "yes"
cb_set "use_ffmpeg_vf" "yes"
cb_set "quick_conv" "yes"
cb_set "server_friendly_conversion" "yes"
cb_set "max_upload_size" "256"
cb_set "mail_type" "smtp"
cb_set "smtp_host" "localhost"
cb_set "ffmpegpath" "/usr/bin/ffmpeg"
cb_set "flvtool2path" "/usr/bin/flvtool2"
cb_set "mp4boxpath" "/usr/bin/MP4Box"

# stop services
/etc/init.d/mysql stop
/etc/init.d/apache2 stop

