#!/bin/bash -e
# regenerate clipbucket mysql password

. /etc/default/inithooks

CONF=/var/www/clipbucket/includes/dbconnect.php
PASSWORD=$(mcookie)
sed -i "s|DBPASS =.*|DBPASS = '$PASSWORD';|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=clipbucket --pass="$PASSWORD"

